# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-28 04:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_choice_choice_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('sex', models.BooleanField(default=0)),
                ('email', models.CharField(max_length=100)),
            ],
        ),
    ]
